Feature project swear price
coding-coworking-club/project_tutorial pull request #6
Opened 2021-02-16 08:59 UTC by Peterorr

2021-02-17 04:10 UTC, Kevinweisl requested changes

2021-02-17 04:10 UTC, Kevinweisl commented on swear_price/src/main.py
> +from text_parser import *
這兩個都是自己寫的 py 檔，建議把 import 進來的 function 放在後面，避免使用 * 號，方便理解

2021-02-20 09:11 UTC, waynehuang1026 commented on swear_price/src/main.py
> +        logging.error(f"error message: {e}")
logging error 可以同一行

2021-02-20 09:12 UTC, waynehuang1026 commented on swear_price/src/scraper.py
> +from time import sleep
這行應該是多的

2021-02-20 09:13 UTC, waynehuang1026 commented on swear_price/src/text_parser.py
> +        return(number)
可以直接 return 0 ?!

2021-02-20 09:13 UTC, waynehuang1026 commented on swear_price/src/text_parser.py
> +        return(number)
應該不用括號?!

2021-02-20 09:14 UTC, waynehuang1026 commented on swear_price/src/text_parser.py
> +        logging.error(f"error message: {e}")
可以一個 logging error

2021-02-20 09:16 UTC, waynehuang1026 commented on swear_price/src/config.ini
> +
整份的空格感覺有點多 尤其結尾?!

2021-02-20 09:21 UTC, Peterorr commented on swear_price/src/main.py
> +        logging.error(f"error message: {e}")
啊啊這個不太懂
是說
`except AttributeError as e: logging.error(f"error message: {e}")`
這樣嗎？

2021-02-20 09:23 UTC, waynehuang1026 commented on swear_price/src/main.py
> +        logging.error(f"error message: {e}")
log.error 不用兩個 可以合成一個

2021-02-24 14:02 UTC, waynehuang1026 approved these changes
LGTM

2021-02-25 06:40 UTC, Kevinweisl approved these changes

2021-02-25 07:13 UTC, merged